# Numpy 
It is a general purpose array- processing package. It provides high performance multidimesnional array obejcts and tools for working with these arrays

Main difference in List and Array in Python is that List is not homogenous but Array is

In [4]:
import numpy as np

In [5]:
my_lst = [1,2,3,4]

In [6]:
type(my_lst) # It gives a list

list

In [7]:
arr = np.array(my_lst) # Adding to numpy array

In [8]:
type(my_lst) # my_lst is still a list

list

In [10]:
type(arr) # but arr is array

numpy.ndarray

In [13]:
arr

array([1, 2, 3, 4])

In [14]:
arr.shape # how many rows and columns

(4,)

In [45]:
list1 = [1,2,3,4,5]
list2 = [2,3,4,5,6]
list3 = [4,5,6,7,8]

In [46]:
arr1 = np.array([list1,list2,list3])

In [47]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [48]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 4, 5],
       [6, 7, 8]])

### Indexing


In [49]:
arr = np.array([1,2,3,4,5,6,7])

In [50]:
arr[5] # starts from 0

6

In [51]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [52]:
arr1[1:,2:] # 1st parameter - the row number, 2nd - the list's index

array([[4, 5, 6],
       [6, 7, 8]])

### Arrange

In [55]:
arr2 = np.arange(0,6,2) # start, stop, step

In [56]:
arr2

array([0, 2, 4])

### linspace
linspace() is quite similar to the Python arange() function. But a difference in between the two is that linspace() uses a sample number instead of a step.

In [58]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### Copy and broadcating
Refference type return

In [59]:
ab = np.array([1,2,3,4,5,6,7])

In [60]:
ab[3:] = 100

In [61]:
ab

array([  1,   2,   3, 100, 100, 100, 100])

## Some other explotory tools

In [62]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
arr<2

array([ True, False, False, False, False, False, False])

In [65]:
arr[arr<2] # This displayes the eleemnt which matches the logic

array([1])

In [64]:
arr*2 # Unlike list, in arrays the number multiplied gets multiplied to all the elemnts numerically

array([ 2,  4,  6,  8, 10, 12, 14])

In [71]:
#Create arrays and reshape
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
# to have an array with 1s and tha paremter says how many 1s and by default its dtype if loat
np.ones(4)

array([1., 1., 1., 1.])

In [75]:
np.ones(4, dtype = int) # to chnage the dtype to int

array([1, 1, 1, 1])

In [80]:
#random distrivution
np.random.rand(4,4)

array([[0.65810413, 0.71038525, 0.17168676, 0.39635999],
       [0.25547961, 0.23173163, 0.34592926, 0.82992409],
       [0.66141256, 0.67796358, 0.17800553, 0.1031559 ],
       [0.77059549, 0.66574328, 0.72543765, 0.62640949]])

In [82]:
np.random.randn(4,4) # random distribution based on standard deviation

array([[-0.25756669, -0.26163435, -1.46156364,  1.51454901],
       [-1.9363565 , -0.27658049, -0.98544049,  1.25133917],
       [-0.37793805,  0.18468805, -0.45911332, -0.78208808],
       [-0.22023537,  0.20925075, -1.89813031,  1.16210357]])

In [84]:
np.random.randint(1,100,8) # Any random integer between 1 to 0 and the size of the array being 8

array([23, 14, 78, 36, 17, 85, 85, 10])

In [89]:
np.random.random_sample((1,5)) #Return random floats in the half-open interval [0.0, 1.0).

array([[0.50875609, 0.04524322, 0.0286155 , 0.28873566, 0.21441396]])

In [90]:
np.random.random_sample((2,5)) # first one being the size of array the second parameter is for how many elemnts in the array

array([[0.75994653, 0.75276089, 0.9779872 , 0.04345269, 0.88323052],
       [0.86575444, 0.13815014, 0.9477212 , 0.6652821 , 0.82879035]])