# '='

In [63]:
lst1 = [1,2,3,4]
lst2 = lst1

In [64]:
lst1, lst2

([1, 2, 3, 4], [1, 2, 3, 4])

In [65]:
lst1[1]=1000

In [66]:
lst1

[1, 1000, 3, 4]

In [67]:
lst2

[1, 1000, 3, 4]

Chnage in lst1 gets refelected in lst2 as well, as they refer to same memory location.

# Shallow Copy

In [68]:
gig = [9,4,5,7]

In [69]:
gig1 =  gig.copy()

In [70]:
gig[1]= 41

In [71]:
gig

[9, 41, 5, 7]

In [72]:
gig1

[9, 4, 5, 7]

Unlike before, with copy function, a new memory location is created for gig1 and all the elements of original gig has been stored in a newmemory location, thus there is no chnage.

In [73]:
gig3 = [[1,2,3,4],[5,6,7,8]]

In [74]:
gig4 = gig3.copy()

In [75]:
gig3[1][0]

5

In [76]:
gig3[1][0] =100

In [77]:
gig3, gig4

([[1, 2, 3, 4], [100, 6, 7, 8]], [[1, 2, 3, 4], [100, 6, 7, 8]])

When it comes to nested list, each list- [1,2,3,4] is being treated like an item rather than where in single list, every elements like 1,2,3,4 are being treated like an item, thus the change gets reflected in both.

# Deep Copy

In [78]:
import copy

In [79]:
lst3 = [1,4,5,6]
lst4 = copy.deepcopy(lst3)

In [80]:
lst3[2]=43

In [81]:
lst3

[1, 4, 43, 6]

In [82]:
lst4

[1, 4, 5, 6]

Just like shallow copy,it works here too. Now, check for nested list

In [83]:
pop = [[1,2,3,4],[5,6,7,8],[4,1,5,6]]

In [84]:
pop2 = copy.deepcopy(pop)

In [85]:
pop[2][0] = 100

In [86]:
pop

[[1, 2, 3, 4], [5, 6, 7, 8], [100, 1, 5, 6]]

In [87]:
pop2

[[1, 2, 3, 4], [5, 6, 7, 8], [4, 1, 5, 6]]

No, change

## Confusion - 

In [88]:
import numpy as np

In [89]:
n = np.array([[1,2,3,4],[4,5,6,7],[3,2,4,5]])

In [90]:
n

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [3, 2, 4, 5]])

In [91]:
n1 = n.copy()

In [92]:
n1

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [3, 2, 4, 5]])

In [93]:
n[1][0] = 300

In [94]:
n

array([[  1,   2,   3,   4],
       [300,   5,   6,   7],
       [  3,   2,   4,   5]])

In [95]:
n1

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [3, 2, 4, 5]])

In [96]:
m = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                   [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])


In [97]:
m1 = m.copy()

In [98]:
m1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [99]:
m1[1][0][1] = 100

In [100]:
m1

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13, 100,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [101]:
m

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [102]:
m[0][2][1] = 100

In [103]:
m

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9, 100,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [104]:
m1

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13, 100,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [105]:
m2 = copy.deepcopy(m)

In [106]:
m[0][1][1] = 500

In [107]:
m

array([[[  1,   2,   3,   4],
        [  5, 500,   7,   8],
        [  9, 100,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [108]:
m2

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9, 100,  11,  12]],

       [[ 13,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [109]:
m1

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 13, 100,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])